export { default as Home } from './Home/Home.jsx'
export { default as About } from './About/About.jsx'
export { default as Login } from './Login/Login.jsx'
export { default as Register } from './Register/Register.jsx'
export { default as CreatePost } from './CreatePost/CreatePost.jsx'
export { default as Dashboard } from './Dashboard/Dashboard.jsx'
export { default as Search } from './Search/Search.jsx'
export { default as Post } from './Post/Post.jsx'